modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
modId="ubran"
version="0.0.1"
displayName="Ubran"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://www.curseforge.com/minecraft/mc-mods/ubran"
authors="CoringPlay, MCreator"

[[dependencies.ubran]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"

[[dependencies.ubran]]
    modId="forge"
    mandatory=true
    versionRange="[40.2.2]"
    ordering="NONE"
    side="BOTH"


[[dependencies.ubran]]
    modId="jade"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ubran]]
    modId="catalogue"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

